### ISSUE TITLE
Issue with the dates in your Website's RSS feeds

### ISSUE THREAD

**Issue by farzadmf** [junegunn/junegunn#1]
Hi, sorry if this is not the proper place to open this issue, but I tried searching for a "github.io" repository and couldn't find it.

Your Website's RSS feed (https://junegunn.github.io/index.xml) has all the dates as `Mon, 01 Jan 0001 00:00:00 +0000`, which is creating issues for my RSS reader picking up [new] articles from the feed.

I was wondering if you're aware of this and if there's a chance to fix it?

**Comment by junegunn** [comment]
Thanks, I'll look into it.

**Comment by farzadmf** [comment]
@junegunn thank you, I appreciate it.

If possible, please let me know if/when it's fixed.

**Comment by junegunn** [comment]
Fixed now. But the `pubDate` of each post may change in the future if I make modifications to the posts. Because I didn't want to manually manage the dates, so I just set it up to use the git commit date of the file.

**Comment by farzadmf** [comment]
Thank you @junegunn ; I appreciate the fix.

My reader is picking up going back to Chrome History (which seems to have been published Aug 01, 2024 [according to the feed](https://junegunn.github.io/index.xml).

Should be good now, and looking forward to your excellent tip articles.
